changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: CI/CD
      labels:
        - ci
        - chore
  exclude:
    labels:
      - skip-changelog
